from __future__ import annotations

from typing import Literal, TypeAlias


IcebergTablePropertyKey: TypeAlias = Literal[
    "read.split.target-size",
    "read.split.metadata-target-size",
    "read.split.planning-lookback",
    "read.split.open-file-cost",
    "read.parquet.vectorization.enabled",
    "read.parquet.vectorization.batch-size",
    "read.orc.vectorization.enabled",
    "read.orc.vectorization.batch-size",
    "write.format.default",
    "write.delete.format.default",
    "write.parquet.row-group-size-bytes",
    "write.parquet.page-size-bytes",
    "write.parquet.page-version",
    "write.parquet.page-row-limit",
    "write.parquet.dict-size-bytes",
    "write.parquet.compression-codec",
    "write.parquet.compression-level",
    "write.parquet.shred-variants",
    "write.parquet.variant-inference-buffer-size",
    "write.parquet.bloom-filter-max-bytes",
    "write.avro.compression-codec",
    "write.avro.compression-level",
    "write.orc.stripe-size-bytes",
    "write.orc.block-size-bytes",
    "write.orc.compression-codec",
    "write.orc.compression-strategy",
    "write.orc.bloom.filter.columns",
    "write.orc.bloom.filter.fpp",
    "write.location-provider.impl",
    "write.metadata.compression-codec",
    "write.metadata.metrics.max-inferred-column-defaults",
    "write.metadata.metrics.default",
    "write.target-file-size-bytes",
    "write.delete.target-file-size-bytes",
    "write.distribution-mode",
    "write.delete.distribution-mode",
    "write.update.distribution-mode",
    "write.merge.distribution-mode",
    "write.wap.enabled",
    "write.summary.partition-limit",
    "write.metadata.delete-after-commit.enabled",
    "write.metadata.previous-versions-max",
    "write.spark.fanout.enabled",
    "write.object-storage.enabled",
    "write.object-storage.partitioned-paths",
    "write.data.path",
    "write.metadata.path",
    "write.delete.mode",
    "write.delete.isolation-level",
    "write.update.mode",
    "write.update.isolation-level",
    "write.merge.mode",
    "write.merge.isolation-level",
    "write.delete.granularity",
    "encryption.key-id",
    "encryption.data-key-length",
    "commit.retry.num-retries",
    "commit.retry.min-wait-ms",
    "commit.retry.max-wait-ms",
    "commit.retry.total-timeout-ms",
    "commit.status-check.num-retries",
    "commit.status-check.min-wait-ms",
    "commit.status-check.max-wait-ms",
    "commit.status-check.total-timeout-ms",
    "commit.manifest.target-size-bytes",
    "commit.manifest.min-count-to-merge",
    "commit.manifest-merge.enabled",
    "history.expire.max-snapshot-age-ms",
    "history.expire.min-snapshots-to-keep",
    "history.expire.max-ref-age-ms",
    "gc.enabled",
    "format-version",
    "comment",
    "compatibility.snapshot-id-inheritance.enabled",
]

TablePropertyKey: TypeAlias = IcebergTablePropertyKey | str
TablePropertyValue: TypeAlias = str | int | bool


__all__ = [
    "IcebergTablePropertyKey",
    "TablePropertyKey",
    "TablePropertyValue",
]
